import type { Metadata } from "next";
import "./globals.css";
import { ToasterProvider } from "@/providers/toast-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <ToasterProvider />
      {children}
    </body>
  </html>
  );
}